### ISSUE TITLE
Unable to find file in AlienLoaded

### ISSUE THREAD

**Issue by hoytech** [Perl5-Alien/Alien-Base-ModuleBuild#1]
See the following issue from @eserte:

https://github.com/hoytech/Alien-LMDB/issues/4

The system had an existing copy of LMDB, which it seems it found via pkg-config. Perhaps the system is misconfigured? If so, sorry for the noise.

**Comment by plicease** [comment]
Instead of testing the output of particular flags I suggest using Test::Alien to test your Alien with real XS code.  Example:

https://github.com/plicease/Alien-Editline/blob/master/t/xs.t
