### ISSUE TITLE
Tests fail with standard perl on openSUSE

### ISSUE THREAD

**Issue by stoecker** [Perl5-Alien/Alien-Base-ModuleBuild#8]
Hi,

on newer openSUSE systems this package fails with following test:

> Failed test 'found privateapp in path'
> at t/alien_base_modulebuild.t line 225.

Probably this is because "." is not in the default search path.

See log:
https://build.opensuse.org/package/live_build_log/devel:languages:perl/perl-Alien-Base-ModuleBuild/openSUSE_Tumbleweed/i586

**Comment by plicease** [comment]
I'd say it is more likely this:

```
[   15s] + find . -type f '!' -name '*.pl' -print0
[   15s] + xargs -0 chmod 644
```

`./corpus/alien_base_modulebuild/bin/privateapp` (not in '.') needs to be executable, you shouldn't be removing the execute bit from members of the distribution.

**Comment by stoecker** [comment]
Sorry. That line is required by so many modules to get rid of wrong permissions later that I overlooked it in trouble shooting. Works fine without this line. Thanks.
